# --------------------------------------------------------------------------
# THIS FILE IS AUTOGENERATED - DO NOT EDIT MANUALLY
#
# Source: Containerfile.j2
# --------------------------------------------------------------------------

# syntax=docker/dockerfile:1
ARG BASE_VERSION=15

# Extract pre-built app from official upstream image
FROM --platform=linux/amd64 ghcr.io/gethomepage/homepage:latest AS upstream

FROM ghcr.io/daemonless/base:${BASE_VERSION}

ARG UPSTREAM_URL="https://api.github.com/repos/gethomepage/homepage/releases/latest"
ARG UPSTREAM_JQ=".tag_name"
ARG HEALTHCHECK_ENDPOINT="http://localhost:3000/"

ENV HEALTHCHECK_URL="${HEALTHCHECK_ENDPOINT}"

# --- Metadata (Injected by Generator) ---
LABEL org.opencontainers.image.title="Homepage" \
      org.opencontainers.image.description="Modern, fully static, fast, secure and highly customizable application dashboard with integrations for over 100 services." \
      org.opencontainers.image.source="https://github.com/daemonless/homepage" \
      org.opencontainers.image.url="https://gethomepage.dev/" \
      org.opencontainers.image.licenses="GPL-3.0" \
      org.opencontainers.image.vendor="daemonless" \
      org.opencontainers.image.authors="daemonless" \
      io.daemonless.category="Utilities" \
      io.daemonless.port="3000" \
      io.daemonless.volumes="/config" \
      io.daemonless.upstream-mode="source" \
      io.daemonless.upstream-url="${UPSTREAM_URL}" \
      io.daemonless.upstream-jq="${UPSTREAM_JQ}" \
      io.daemonless.healthcheck-url="${HEALTHCHECK_ENDPOINT}"

# Install runtime dependency only
RUN pkg update && \
    pkg install -y node22 && \
    pkg clean -ay && \
    rm -rf /var/cache/pkg/* /var/db/pkg/repos/*

# Copy pre-built app from official upstream image
WORKDIR /app
COPY --from=upstream /app/ /app/

# Write version from package.json
RUN node -e "process.stdout.write(require('/app/package.json').version)" > /app/version

# Create config directory
RUN mkdir -p /config && \
    chown -R bsd:bsd /config /app

# Copy s6 service
COPY root/ /

# Make scripts executable
RUN chmod +x /etc/services.d/homepage/run /etc/cont-init.d/*

# --- Expose (Injected by Generator) ---
EXPOSE 3000

# --- Volumes (Injected by Generator) ---
VOLUME /config